# Generated by Django 3.0.3 on 2020-02-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_reg_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
