# Generated by Django 3.0.3 on 2020-07-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_solution', models.FileField(blank=True, null=True, upload_to='', verbose_name='Решение')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='homework_solution',
        ),
        migrations.AddField(
            model_name='course',
            name='info',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pupils',
            field=models.ManyToManyField(blank=True, null=True, to='cabinet.Pupil', verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='cabinet.Teacher', verbose_name='Учителя'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabinet.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='group',
            name='day',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='День занятия'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pupils',
            field=models.ManyToManyField(to='cabinet.Pupil', verbose_name='Ученики'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cabinet.Teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Время проведения занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabinet.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework_task',
            field=models.TextField(blank=True, null=True, verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.TextField(blank=True, null=True, verbose_name='материалы к уроку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pupils',
            field=models.ManyToManyField(to='cabinet.Pupil', verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabinet.Teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефонный номер'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(hours__gte=0), name='hours_gte_0'),
        ),
        migrations.AddField(
            model_name='solution',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabinet.Lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='solution',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabinet.Pupil', verbose_name='Ученик'),
        ),
    ]
