# Generated by Django 3.0.3 on 2020-02-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pupils',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
    ]
