# Generated by Django 3.0.3 on 2020-02-23 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20200224_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pupils',
            field=models.ManyToManyField(to='cabinet.Pupil', verbose_name='ученики'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Teacher', verbose_name='Учитель'),
        ),
    ]
