# Generated by Django 3.0.3 on 2020-02-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_auto_20200226_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='pupils',
            field=models.ManyToManyField(blank=True, null=True, to='cabinet.Pupil'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='cabinet.Teacher'),
        ),
    ]
